Add MaxConcurrentConnections in config.json
neo-project/neo-node pull request #655
Opened 2020-08-25 10:29 UTC by superboyiii

Need [neo#1873](https://github.com/neo-project/neo/pull/1873)

2020-08-25 14:33 UTC, shargon approved these changes
Wait for https://github.com/neo-project/neo/pull/1873

2020-08-29 06:15 UTC, shargon approved these changes

2020-08-31 08:55 UTC, superboyiii commented
@shargon A little mistake, I've just fixed it.

2020-08-31 10:58 UTC, shargon approved these changes

2020-08-31 11:00 UTC, shargon commented
https://github.com/neo-project/neo/pull/1887 was merged, @superboyiii could you update the nuget ?

2020-09-01 02:26 UTC, superboyiii commented
> [neo-project/neo#1887](https://github.com/neo-project/neo/pull/1887) was merged, @superboyiii could you update the nuget ?

Sure.

2020-09-09 06:20 UTC, erikzhang requested changes
The configuration files and the default value must be consistent.

2020-09-09 06:51 UTC, superboyiii commented
> The configuration files and the default value must be consistent.

Done

2020-09-09 06:59 UTC, erikzhang commented on neo-cli/Settings.cs
> +            this.MaxConcurrentConnections = int.Parse(section.GetValue("MaxConcurrentConnections", "120"));
`120` is too high for normal use.

```suggestion
            this.MaxConcurrentConnections = int.Parse(section.GetValue("MaxConcurrentConnections", "10"));
```

2020-09-09 07:06 UTC, superboyiii commented on neo-cli/Settings.cs
> +            this.MaxConcurrentConnections = int.Parse(section.GetValue("MaxConcurrentConnections", "120"));
> MaxConcurrentConnections

`10` concurrency is too low for a full node rpc. Mainnet seed nodes is meeting more than `40` concurrency now. And rising it to this amount doesn't influence node stability or performance.

2020-09-09 07:12 UTC, erikzhang commented on neo-cli/Settings.cs
> +            this.MaxConcurrentConnections = int.Parse(section.GetValue("MaxConcurrentConnections", "120"));
You can change the configuration file for seed nodes. But the default settings of the configuration files should suit the needs of normal users.

2020-09-09 07:56 UTC, superboyiii commented on neo-cli/Settings.cs
> +            this.MaxConcurrentConnections = int.Parse(section.GetValue("MaxConcurrentConnections", "120"));
> You can change the configuration file for seed nodes. But the default settings of the configuration files should suit the needs of normal users.

Fine.

2020-09-09 08:22 UTC, erikzhang approved these changes

2020-09-09 11:38 UTC, vncoelho approved these changes

2020-09-09 17:00 UTC, shargon approved these changes

2020-09-09 17:00 UTC, merged