dotnet 5.0
neo-project/neo-node pull request #681
Opened 2020-11-23 08:14 UTC by chenzhitong

2020-11-23 14:30 UTC, shargon approved these changes
wait for preview4

2020-11-24 17:27 UTC, vncoelho commented on Directory.Build.props
> +    <VersionSuffix>preview3</VersionSuffix>
To change.

2020-11-24 17:27 UTC, vncoelho commented on Dockerfile
>  RUN apt-get update && apt-get install -y \
`5.0.100` as well?

2020-11-24 21:07 UTC, snowypowers commented on Dockerfile
>  RUN apt-get update && apt-get install -y \
Btw, they updated the namespaces for their docker images. See https://github.com/dotnet/dotnet-docker/issues/2375

The new one should be `mcr.microsoft.com/dotnet/runtime:5.0` (or whatever version you want)

2020-11-25 05:54 UTC, snowypowers commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/runtime:5.0.0 AS Build
```suggestion
FROM mcr.microsoft.com/dotnet/sdk:5.0.0 AS Build
```

2020-12-21 08:36 UTC, shargon commented on Directory.Build.props
> +    <VersionSuffix>preview3</VersionSuffix>
Done

2020-12-21 08:37 UTC, shargon submitted a review, later dismissed

2020-12-21 18:59 UTC, vncoelho commented on Directory.Build.props
> +    <VersionSuffix>preview4</VersionSuffix>
change `VersionSuffix`?

2020-12-21 19:02 UTC, vncoelho commented on neo-cli/neo-cli.csproj
>  <Project Sdk="Microsoft.NET.Sdk">
Change `<PackageReference Include="Neo" Version="3.0.0-preview4" />` ?

2020-12-22 03:04 UTC, erikzhang requested changes

2020-12-22 03:04 UTC, erikzhang commented on .github/workflows/dotnetcore.yml
> +        ./dotnet-format neo-cli --check -v diagnostic
```suggestion
        ./dotnet-format --check -v diagnostic
```

2020-12-22 03:04 UTC, erikzhang commented on Directory.Build.props
> +﻿<?xml version="1.0" encoding="utf-8"?>
I think we don't need `Directory.Build.props`.

2020-12-22 04:51 UTC, erikzhang approved these changes

2020-12-22 04:51 UTC, merged