Max traceable blocks
neo-project/neo-node pull request #682
Opened 2020-11-25 03:39 UTC by chenzhitong

2020-11-25 11:28 UTC, shargon approved these changes

2020-11-25 11:29 UTC, shargon requested changes

2020-11-25 11:29 UTC, shargon commented on neo-cli/protocol.mainnet.json
> +    "MaxTraceableBlocks": 5760,
By default it's other value
https://github.com/neo-project/neo/blob/402e9b19d80bb9093601f5ac57ff0cdc3c6cf6ab/src/neo/ProtocolSettings.cs#L98

2020-11-25 14:03 UTC, vncoelho reviewed
It should be something around `2102400` equals to 365 days.

2020-11-25 14:07 UTC, vncoelho commented on neo-cli/protocol.json
> +    "MaxTraceableBlocks": 5760,
This is one day currently, right?
If nodes miss syncronization it would require `import`

2020-11-26 08:59 UTC, shargon approved these changes

2020-11-30 06:30 UTC, merged