Add test mode gas when invoking
neo-project/neo-node pull request #727
Opened 2021-01-25 09:04 UTC by bettybao1209

close https://github.com/neo-project/neo/issues/2260

2021-01-25 10:10 UTC, shargon approved these changes

2021-01-25 10:16 UTC, shargon commented on neo-cli/CLI/MainService.cs
>          /// <param name="contractParameters">Contract parameters</param>
Add comments?

2021-01-25 10:29 UTC, bettybao1209 commented on neo-cli/CLI/MainService.cs
>          /// <param name="contractParameters">Contract parameters</param>
Updated.

2021-01-25 11:24 UTC, shargon commented on neo-cli/CLI/MainService.cs
>          /// <param name="contractParameters">Contract parameters</param>
Please add for `showStack` too

2021-01-26 02:20 UTC, bettybao1209 commented on neo-cli/CLI/MainService.cs
>          /// <param name="contractParameters">Contract parameters</param>
Done.

2021-01-26 02:45 UTC, erikzhang approved these changes

2021-01-26 07:56 UTC, superboyiii requested changes
https://github.com/bettybao1209/neo-node/blob/a85b767e76a62a0343c1b276743f1b4199bd1041/neo-cli/CLI/MainService.cs#L488
Please change here like: `using (ApplicationEngine engine = ApplicationEngine.Run(tx.Script, container: tx, gas:1010_00000000))`, it was called by `register candidates` method straightly. This is what I need.

2021-01-26 08:28 UTC, shargon submitted a review, later dismissed

2021-01-26 10:43 UTC, bettybao1209 commented
> Please change here like: `using (ApplicationEngine engine = ApplicationEngine.Run(tx.Script, container: tx, gas:1010_00000000))`, it was called by `register candidates` method straightly. This is what I need.

There are two ways to register a candidate, so I updated both the `invoke` and `register candidate` commands. Also, I have to add the `TestModeGas` in `MakeTransaction` method since it also runs the script. Please review again.

2021-01-26 11:57 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +        private void OnInvokeCommand(UInt160 scriptHash, string operation, JArray contractParameters = null, UInt160 sender = null, UInt160[] signerAccounts = null, string gas = null)
Use `BigDecimal`?

2021-01-26 14:53 UTC, bettybao1209 commented on neo-cli/CLI/MainService.Contracts.cs
> +        private void OnInvokeCommand(UInt160 scriptHash, string operation, JArray contractParameters = null, UInt160 sender = null, UInt160[] signerAccounts = null, string gas = null)
I parsed the string to BigDecimal in the next few lines.

2021-01-26 15:03 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +        private void OnInvokeCommand(UInt160 scriptHash, string operation, JArray contractParameters = null, UInt160 sender = null, UInt160[] signerAccounts = null, string gas = null)
I mean as argument, instead of string BigDecimal, and allow them as a new type

2021-01-26 15:31 UTC, superboyiii commented on neo-cli/CLI/MainService.cs
> +        private void SendTransaction(byte[] script, UInt160 account = null, long gas = TestModeGas)
I think no need to add extra TestModeGas as an optional param here. It's not invokefunction. This made it more complex. The system fee of registering candidates is a a certain value -> about 1000 gas.
https://github.com/neo-project/neo/blob/677bd9648d40b31076ba78c88c8a48bc0e919f66/src/neo/SmartContract/Native/NeoToken.cs#L212
So 1000 gas + 20 test gas is enough. If you do it optional here, users will not know how much to input. We should not throw the problem to user.

2021-01-26 15:47 UTC, bettybao1209 commented on neo-cli/CLI/MainService.cs
> +        private void SendTransaction(byte[] script, UInt160 account = null, long gas = TestModeGas)
SendTransaction is also called by other commands，of which the test mode gas are different. Also，this method should be apparent to users.

2021-01-26 17:50 UTC, superboyiii commented on neo-cli/CLI/MainService.cs
> +        private void SendTransaction(byte[] script, UInt160 account = null, long gas = TestModeGas)
> SendTransaction is also called by other commands，of which the test mode gas are different. Also，this method should be transparent to users.

Only vote related methods are using `SendTransaction`, 1020 gas will not cause any malicious attack since it's a user behaviour . But if we make it optional here, it will not be transparent but just confusion.

2021-01-30 09:21 UTC, bettybao1209 commented
1. Insufficient gas (two signers + default gas):
 `invoke 0xf61eebf573ea36593fd43aa150c055ad7906ab83 registerCandidate [{"type":"PublicKey","value":"03d922481a6190c0afdc200600abec944d5b588a6fe6ef9639cc28be3493319b0d"}] NaqFR6Qv3VM3XWLLqbuK6PwRi9uYGGDk1e NMbT8LVG9aLdKs3HBzf5LvV2XBqjjjjpeR,NUjGMLwcYZuhUSTeNcZSvYkrQRciAhnFET`
 
 2. succeed (+ 1010 gas) :
` invoke 0xf61eebf573ea36593fd43aa150c055ad7906ab83 registerCandidate [{"type":"PublicKey","value":"03d922481a6190c0afdc200600abec944d5b588a6fe6ef9639cc28be3493319b0d"}] NaqFR6Qv3VM3XWLLqbuK6PwRi9uYGGDk1e NMbT8LVG9aLdKs3HBzf5LvV2XBqjjjjpeR 1010`
 
 3. succeed (+ null) ：
 `export key null 0x75b75932a1451cc0c56a95eff7fcc01de45aa5a3`

2021-01-30 10:01 UTC, bettybao1209 commented
wait for https://github.com/neo-project/neo-node/pull/733

2021-01-31 03:43 UTC, Tommo-L commented on neo-cli/CLI/MainService.Contracts.cs
> +            var value = BigDecimal.Parse(maxGas.ToString(CultureInfo.InvariantCulture), NativeContract.GAS.Decimals);
```suggestion
            var fee = BigDecimal.Parse(maxGas.ToString(CultureInfo.InvariantCulture), NativeContract.GAS.Decimals);
```

2021-01-31 03:46 UTC, Tommo-L commented on neo-cli/CLI/MainService.cs
> +
```suggestion
```

2021-01-31 04:33 UTC, bettybao1209 commented on neo-cli/CLI/MainService.Contracts.cs
> +            var value = BigDecimal.Parse(maxGas.ToString(CultureInfo.InvariantCulture), NativeContract.GAS.Decimals);
Done.

2021-01-31 04:36 UTC, Tommo-L submitted a review, later dismissed

2021-01-31 08:48 UTC, shargon commented on Neo.ConsoleService/CommandToken.cs
> +            for (int i = args.Count - 1; i >= 0; i--)
This will move the arguments and it could be a little random

2021-01-31 08:48 UTC, shargon commented on neo-cli/CLI/MainService.Vote.cs
> +        public const uint RegisterGas = 1010;
```suggestion
        public const uint RegisterGas = 1010;

```

2021-01-31 09:47 UTC, bettybao1209 commented on Neo.ConsoleService/CommandToken.cs
> +            for (int i = args.Count - 1; i >= 0; i--)
Here I remove all space items in the args list at one time so we don't have to trim the string for each parameter. But the side effect is that we should use the `comma` to separate the string array as defined in https://github.com/neo-project/neo-node/blob/master/Neo.ConsoleService/ConsoleServiceBase.cs#L414.

2021-01-31 11:14 UTC, bettybao1209 commented on Neo.ConsoleService/CommandToken.cs
> +            for (int i = args.Count - 1; i >= 0; i--)
Maybe we should focus on adding the gas feature in this pr, so I revert the change.

2021-02-01 07:13 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = BigDecimal.Parse(maxGas.ToString(CultureInfo.InvariantCulture), NativeContract.GAS.Decimals);
We shouldn't use `BigDecimal.Parse()` here. Use the constructor directly.

2021-02-01 07:25 UTC, bettybao1209 commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = BigDecimal.Parse(maxGas.ToString(CultureInfo.InvariantCulture), NativeContract.GAS.Decimals);
Done.

2021-02-01 07:37 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +        private void OnInvokeCommand(UInt160 scriptHash, string operation, JArray contractParameters = null, UInt160 sender = null, UInt160[] signerAccounts = null, decimal maxGas = 20)
I think maybe we should use `long` uniformly. I see that we currently use `long` in some places and `decimal` in other places. This is easy to confuse.

2021-02-01 08:00 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
This variable is no more needed.

2021-02-01 08:05 UTC, bettybao1209 commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
You mean we should take the gas input like `2000000000`  as `20`?

2021-02-01 08:06 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
Yes.

2021-02-01 08:07 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
Maybe we use `decimal` for user input?

2021-02-01 08:28 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
I think that it's easier to use decimal for users

2021-02-01 08:30 UTC, erikzhang commented on neo-cli/CLI/MainService.Contracts.cs
> +            var gas = new BigDecimal((decimal)maxGas, NativeContract.GAS.Decimals);
So, for the user interface, we use `decimal`. For the program interface, we use long.

2021-02-01 09:02 UTC, erikzhang approved these changes

2021-02-01 09:10 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +        /// <param name="gas">Max fee for running the script</param>
```suggestion
        /// <param name="masGas">Max fee for running the script</param>
```

2021-02-01 09:10 UTC, shargon approved these changes

2021-02-01 09:12 UTC, erikzhang approved these changes

2021-02-01 09:26 UTC, superboyiii approved these changes

2021-02-01 09:28 UTC, merged