Copyright in files
neo-project/neo-node pull request #813
Opened 2021-08-15 10:51 UTC by Liaojinghui

2021-08-16 19:34 UTC, vncoelho commented
Looks, good, I think @erikzhang should double check it.

2021-08-17 02:49 UTC, shargon submitted a review, later dismissed
Look good, but maybe redundant with the LICENSE file

2021-08-17 03:18 UTC, Liaojinghui commented
> Look good, but maybe redundant with the LICENSE file

On the contrary, the LICENSE file is far from enough for a public open-source project that welcomes contributions from the community and allows anyone to use its code. To the best of my knowledge, all open source projects as famous as neo have in-file copyright and license declaration.

2021-08-17 08:06 UTC, superboyiii submitted a review, later dismissed

2021-08-17 08:17 UTC, superboyiii commented
@erikzhang Merge?

2021-08-18 08:52 UTC, erikzhang requested changes

2021-08-18 08:52 UTC, erikzhang commented on Neo.ConsoleService/CommandQuoteToken.cs
> +// Copyright (C) 2016-2021 NEO GLOBAL DEVELOPMENT.
```suggestion
// Copyright (C) 2016-2021 The Neo Project.
```

2021-08-18 09:16 UTC, erikzhang commented on Neo.ConsoleService/CommandQuoteToken.cs
> +// The neo-consolservice is free software distributed under the MIT software license,
```suggestion
// The Neo.ConsoleService is free software distributed under the MIT software license, 
```

2021-08-18 09:42 UTC, erikzhang commented on neo-cli/CLI/ConsolePercent.cs
> +// The Neo.CLI is free software distributed under the MIT software
```suggestion
// The neo-cli is free software distributed under the MIT software 
```

It should be the same as the project name.

2021-08-19 05:45 UTC, erikzhang approved these changes

2021-08-19 06:32 UTC, shargon approved these changes

2021-08-19 06:32 UTC, merged