typo, comment, code optimization.
neo-project/neo-node pull request #847
Opened 2022-01-20 02:13 UTC by Liaojinghui

2022-01-20 09:27 UTC, shargon requested changes

2022-01-20 09:27 UTC, shargon commented on neo-cli/CLI/ConsolePercent.cs
> +        private long MaxValue
Please don't change visiblities

2022-01-20 09:27 UTC, shargon commented on Neo.ConsoleService/ConsoleColorSet.cs
> +        private readonly ConsoleColor _foreground;
Please don't change visiblities

2022-01-25 07:29 UTC, erikzhang commented on Neo.ConsoleService/ConsoleServiceBase.cs
> +                    process?.WaitForExit();
I think we should throw the exception here instead of ignoring it. The easiest way is to remove the question mark.

2022-01-26 06:31 UTC, erikzhang commented on neo-cli/CLI/Logger.cs
> +        public override string ConfigFile => Combine(GetDirectoryName(Path) ?? throw new InvalidOperationException(), "config.json");
Why do we need this?

2022-01-26 06:31 UTC, erikzhang commented on neo-cli/CLI/Logger.cs
> +            while (true)
What's the difference?

2022-01-26 15:55 UTC, Liaojinghui commented on neo-cli/CLI/Logger.cs
> +        public override string ConfigFile => Combine(GetDirectoryName(Path) ?? throw new InvalidOperationException(), "config.json");
Cause the return value of function `GetDirectoryName` is nullable:

`public static string? GetDirectoryName(string? path)`

2022-01-26 15:59 UTC, Liaojinghui commented on neo-cli/CLI/Logger.cs
> +            while (true)
Compared to loop, recursion is an inefficient algorithm, that is why we should avoid using recursion as much as possible.

2022-01-27 03:11 UTC, Liaojinghui commented on neo-cli/CLI/Logger.cs
> +            while (true)
almost removed all changes that has nothing to do with the typo and comments, realized that this pr contains too much that is not important at all.

2022-01-27 08:35 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +        /// <param name="data"></param>
```suggestion
        /// <param name="data">Extra data for deploy</param>
```

2022-01-27 08:35 UTC, shargon commented on neo-cli/CLI/MainService.Contracts.cs
> +        /// <param name="data"></param>
```suggestion
        /// <param name="data">Extra data for update</param>
```

2022-01-27 08:35 UTC, shargon commented on neo-cli/CLI/MainService.Node.cs
> +                // ignored
I think that this comment is not needed

2022-01-27 14:38 UTC, Liaojinghui commented on Neo.ConsoleService/ConsoleServiceBase.cs
> +                }
```suggestion
                catch { }
```

2022-01-27 15:21 UTC, shargon approved these changes

2022-01-30 03:06 UTC, erikzhang commented on neo-cli/CLI/Logger.cs
> +        public override string ConfigFile => Combine(GetDirectoryName(Path) ?? throw new InvalidOperationException(), "config.json");
But it makes no difference. If it is `null`, then `Combine` method will throw an exception.

2022-01-30 14:45 UTC, erikzhang commented on neo-cli/CLI/Logger.cs
> +                            throw new ArgumentOutOfRangeException(nameof(level), level, null);
Why not just ignore it?

2022-03-27 04:55 UTC, erikzhang commented on neo-cli/CLI/MainService.Node.cs
> +            }, cancel.Token);
It's not necessary. Because it is already judged in the loop.

2022-03-29 02:43 UTC, erikzhang approved these changes

2022-03-31 09:16 UTC, merged